export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER'
export const SET_DATE_RANGE_FILTER = 'SET_DATE_RANGE_FILTER'